package timaxa007.show_name_entity_item;

import com.google.common.collect.Lists;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = ShowNameEntityItemMod.MODID, name = ShowNameEntityItemMod.NAME, version = ShowNameEntityItemMod.VERSION, useMetadata = true, guiFactory = "timaxa007.show_name_entity_item.GuiFactory")
public class ShowNameEntityItemMod {

	public static final String
	MODID = "show_name_entity_item",
	NAME = "Show Name Item Mod",
	VERSION = "0.2";

	@Mod.Instance(MODID)
	public static ShowNameEntityItemMod instance;
	
	@Mod.Metadata(MODID)
	public static ModMetadata metadata;

	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		metadata = metadata(event.getModMetadata());
		Config.init(event.getSuggestedConfigurationFile());
		MinecraftForge.EVENT_BUS.register(new EventsForge());
	}

	public ModMetadata metadata(ModMetadata metadata) {
		metadata.authorList = Lists.newArrayList("timaxa007");
		metadata.modId = MODID;
		metadata.name = NAME;
		metadata.version = VERSION;
		metadata.autogenerated = false;
		return metadata;
	}

}
